### ISSUE TITLE
Tasks fail in a project using version 4.0.0 of the Android Gradle Plugin

### ISSUE THREAD

**Issue by jschear** [airbnb/okreplay#106]
After upgrading to AGP 4.0.0, our `clear<variant>OkReplayTapes` task is failing with a `NoClassDefFoundError`. It looks like `ConnectedDeviceProvider` was moved to the `com.android.build.gradle.internal.testing` package.

I tried upgrading the AGP dependency in OkReplay, but it's going to take a bit of work -- it requires Gradle 6.1.1 at a minimum, but https://github.com/groovy/groovy-android-gradle-plugin isn't compatible with Gradle 6 (and it is no longer maintained), so the tests in the `okreplay-tests` project will probably need to be migrated to Java or Kotlin.

I think the best move here is to access the device providers through AGP's`BaseExtension#deviceProviders` API instead of instantiating them directly, which looks like it should work on AGP 3.6.0 and 4.0.0. I'm working on a PR to do that.

Stacktrace:
```
jschear ~/dev/slack-android-ng (master) $ ./gradlew app:clearInternalDebugOkReplayTapes --stacktrace
> Task :app:clearInternalDebugOkReplayTapes FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:clearInternalDebugOkReplayTapes'.
> com/android/builder/testing/ConnectedDeviceProvider

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:clearInternalDebugOkReplayTapes'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:207)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:205)
        ...
Caused by: java.lang.NoClassDefFoundError: com/android/builder/testing/ConnectedDeviceProvider
        at okreplay.DeviceBridge.<init>(DeviceBridge.kt:10)
        at okreplay.DeviceBridgeProvider$Companion.get$okreplay_gradle_plugin(DeviceBridgeProvider.kt:15)
        at okreplay.ClearTapesTask.clearTapes$okreplay_gradle_plugin(ClearTapesTask.kt:16)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        ...
```

**Comment by stopdrake** [comment]
Hey @jschear. We are facing this same problem after upgrading to AGP 4.0.0 . Were you able to solve this or have a workaround?

**Comment by jschear** [comment]
Unfortunately I haven't -- I actually stopped using OkReplay for separate reasons soon after this issue popped up. I think I have a pretty good idea of what needs to be done to fix this issue, though (adopting the `BaseExtension#deviceProviders` API), and I may have some time this weekend to work on a PR.

**Comment by jschear** [comment]
I think I was wrong about moving to the `BaseExtension#deviceProviders` being a solution -- that function returns an empty list when I test locally, and it appears to be an extension point for adding other, custom `DeviceProvider`s.

I see a few ways forward here:
- Do some sort of reflection to load the `DeviceProvider` class from the correct package depending on the version of AGP that's on the classpath.
- Copy `ConnectedDeviceProvider` into okreplay's source tree and call it a day.

@felipecsl, @rossbacher do either of you have an opinion here?

**Comment by rajab57** [comment]
Is this issue resolved ? I am encountering similar issue.
I am exploring okreplay to use in my project at this point.

**Comment by stopdrake** [comment]
For anyone who might want to use OKReplay in there project with AGP >= 4.0 I followed @jschear steps but instead of fixing the `okreplay-tests` for reasons mentioned by him I removed that module from settings.gradle while building.

Please note this is not an official solution and something I did to get it working in my project.
You can find the gist here - https://gist.github.com/stopdrake/0e6607d4a12112d1909320eacf5245cc

Steps to run

1. Copy the jar file to a `gradleLibs` or `libs` directory inside your module
2. In your module level build.gradle add classpath to your buildscript dependencies like below
```
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
//      classpath "com.airbnb.okreplay:gradle-plugin:$okreplay_gradle"
        classpath files('gradlelibs/okreplay-gradle-plugin-1.6.0.jar')
    }
}
```

**Comment by mfekim** [comment]
Like @rajab57, I would like to use OkReplay, but it's not working with AGP >= 4.0 :(

The @stopdrake's solution seems to work but it would be nice if you can fix it

**Comment by KatieBarnett** [comment]
The above workaround seems to have stopped working, I now get this error:

```
Execution failed for task ':app:clear<variant>OkReplayTapes'.
> 'void com.android.build.gradle.internal.testing.ConnectedDeviceProvider.<init>(java.io.File, int, com.android.utils.ILogger)'
```

I am using the following versions:
OkReplay: 1.6.0 (both workaround, and official version)
AGP: 7.1.0-alpha05
AndroidX Test: 1.4.0
Espresso: 3.4.0

**Comment by KatieBarnett** [comment]
I have also tried the above and get the same error with:
OkReplay: 1.6.0 (both workaround, and official version)
AGP: 7.1.2
AndroidX Test: 1.4.0
Espresso: 3.4.0

Please fix this as it is holding our project up from upgrading the gradle plugin.
